<a href="https://www.kaggle.com/code/nerdyalgorithm/dataraflow-week-6-numpy-pandas1?scriptVersionId=271813762" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

![](https://cdn.hashnode.com/res/hashnode/image/upload/v1761505817817/011cbf49-8fd7-412b-9639-de387054e0c0.png?w=1600&h=840&fit=crop&crop=entropy&auto=compress,format&format=webp)

## Task

In [1]:
#imports
import numpy as np
import pandas as pd

In [2]:
import warnings
warnings.filterwarnings("ignore", category=RuntimeWarning)
print("Warning filters have been set.")


Warning filters have been set.


---
```1``` Write a NumPy program to test element-wise for NaN of a given array.
   

In [3]:
# Create an array with a NaN value
a = np.array([1, 0, np.nan, 5])
print("Original array:")
print(a)

# Test for NaN element-wise
print("\nTesting for NaN:")
print(np.isnan(a))

Original array:
[ 1.  0. nan  5.]

Testing for NaN:
[False False  True False]


---
``` 2 ``` Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.

In [4]:

# Create an array with different data types
a = np.array([1 + 1j, 1 + 0j, 5.2, 7])
print("Original array:")
print(a)

# Test for complex numbers
print("\nIs the number complex?")
print(np.iscomplex(a))

# Test for real numbers
print("\nIs the number real?")
print(np.isreal(a))

# Test if a number is a scalar type
print("\nIs 3.1 a scalar?")
print(np.isscalar(3.1))

print("\nIs [3.1] a scalar?")
print(np.isscalar([3.1]))

Original array:
[1. +1.j 1. +0.j 5.2+0.j 7. +0.j]

Is the number complex?
[ True False False False]

Is the number real?
[False  True  True  True]

Is 3.1 a scalar?
True

Is [3.1] a scalar?
False


---
```3``` Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.

In [5]:

# Create two arrays that are close but not exactly equal
a1 = np.array([0.1, 0.2, 0.3])
a2 = np.array([0.100001, 0.200002, 0.300003])
a3 = np.array([0.1, 0.3, 0.4])

print("Array 1:", a1)
print("Array 2:", a2)
print("Array 3:", a3)

# Test if a1 and a2 are equal within a tolerance
print("\nAre a1 and a2 close?", np.allclose(a1, a2))

# Test if a1 and a3 are equal within a tolerance
print("Are a1 and a3 close?", np.allclose(a1, a3))

Array 1: [0.1 0.2 0.3]
Array 2: [0.100001 0.200002 0.300003]
Array 3: [0.1 0.3 0.4]

Are a1 and a2 close? True
Are a1 and a3 close? False


---
```4``` Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [6]:
a = np.array([1, 8, 3, 5])
b = np.array([6, 2, 9, 5])
print("Array a:", a)
print("Array b:", b)

# Perform comparisons
print("\na > b")
print(np.greater(a, b))

print("\na >= b")
print(np.greater_equal(a, b))

print("\na < b")
print(np.less(a, b))

print("\na <= b")
print(np.less_equal(a, b))

Array a: [1 8 3 5]
Array b: [6 2 9 5]

a > b
[False  True False False]

a >= b
[False  True False  True]

a < b
[ True False  True False]

a <= b
[ True False  True  True]


---
```5``` Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.

In [7]:

a = np.array([1, 2, 3, 4.000001])
b = np.array([1, 5, 3, 4.0])
print("Array a:", a)
print("Array b:", b)

# Check for exact equality
print("\nAre arrays equal? (element-wise)")
print(np.equal(a, b))

# Check for equality within a tolerance
print("\nAre arrays equal within a tolerance?")
print(np.allclose(a, b))

Array a: [1.       2.       3.       4.000001]
Array b: [1. 5. 3. 4.]

Are arrays equal? (element-wise)
[ True False  True False]

Are arrays equal within a tolerance?
False


---
```6``` Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.  

In [8]:
#create an array 

arr = np.array([1, 7, 13, 105])
print(f"Array: {arr}")

#memory size 
print(f"Total Memory (nbytes): {arr.nbytes}")

Array: [  1   7  13 105]
Total Memory (nbytes): 32


---
```7``` In the code cell below, write the code to get and display the 55th row in the dataframe df.

**ANSWER**:      ``` df.iloc[54] ```

---
```8``` In the code cell below write the code to display the first 10 rows of the dataframe df.

**ANSWER**:      ``` df.head(10) ```

---
```9``` In the code cell below, select and display the first eight rows from the 'Country' and 'TB deaths' columns.

**ANSWER:**

```
# Select rows 0 through 7 from the 'Country' and 'TB deaths' columns
df.loc[0:7, ['Country', 'TB deaths']]
```

---
```10``` In the code cell below write code to find all the rows in df where TB deaths exceed 10000.

**ANSWER:**
```
# Find all rows where 'TB deaths' is greater than 10000
df[df['TB deaths'] > 10000]
```

---
```11``` In the code cell below find all the countries where the Population (1000s) is less than or equal to 50000 or TB deaths are greater than or equal to 20000.

**ANSWER:**

```
# Find rows that meet either condition
df[(df['Population (1000s)'] <= 50000) | (df['TB deaths'] >= 20000)]

```

---
``` END OF TASK```

---

## Assignment

---
```1``` 
Write a Python program to create and display a one-dimensional array-like object containing an array of data using Pandas module.

In [9]:
# Create a one-dimensional array-like object (a Series)
data = [10, 20, 30, 40, 50]
s = pd.Series(data)
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64


---
```2``` Write a Python program to convert a Panda module Series to Python list and it's type.

In [10]:
s = pd.Series([1, 2, 'Python', 3.14])

# Convert Series to Python list
py_list = s.tolist()

print("Pandas Series:")
print(s)
print("\nConverted Python list:")
print(py_list)
print("\nType of converted object:")
print(type(py_list))

Pandas Series:
0         1
1         2
2    Python
3      3.14
dtype: object

Converted Python list:
[1, 2, 'Python', 3.14]

Type of converted object:
<class 'list'>


---
```3``` Write a Python program to add, subtract, multiple and divide two Pandas Series. Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

In [11]:

s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 9])

print("Series 1:")
print(s1)
print("\nSeries 2:")
print(s2)

print("\nAdd:")
print(s1 + s2)

print("\nSubtract:")
print(s1 - s2)

print("\nMultiply:")
print(s1 * s2)

print("\nDivide:")
print(s1 / s2)

Series 1:
0     2
1     4
2     6
3     8
4    10
dtype: int64

Series 2:
0    1
1    3
2    5
3    7
4    9
dtype: int64

Add:
0     3
1     7
2    11
3    15
4    19
dtype: int64

Subtract:
0    1
1    1
2    1
3    1
4    1
dtype: int64

Multiply:
0     2
1    12
2    30
3    56
4    90
dtype: int64

Divide:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


---
```4``` Write a Python program to get the largest integer smaller or equal to the division of the inputs. Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]



In [12]:
s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 9])

print("Floor division result:")
print(s1 // s2)

Floor division result:
0    2
1    1
2    1
3    1
4    1
dtype: int64


---
```5``` Write a Python program to convert a dictionary to a Pandas series. Sample Series: Original dictionary: {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800} Converted series: a 100 b 200 c 300 d 400 e 800 dtype: int64

In [13]:
# Original dictionary
d = {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}

# Convert dictionary to Series
s = pd.Series(d)

print("Converted series:")
print(s)

Converted series:
a    100
b    200
c    300
d    400
e    800
dtype: int64


---
```6``` Write a Python program to convert a NumPy array to a Pandas series. Sample Series: NumPy array: [10 20 30 40 50] Converted Pandas series: 0 10 1 20 2 30 3 40 4 50 dtype: int64

In [14]:
# NumPy array
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)

# Convert NumPy array to Pandas Series
pd_series = pd.Series(np_array)
print("\nConverted Pandas series:")
print(pd_series)

NumPy array:
[10 20 30 40 50]

Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64


---
```7``` Write a Python program to change the data type of given a column or a Series. Sample Series: Original Data Series: 0 100 1 200 2 python 3 300.12 4 400 dtype: object Change the said data type to numeric: 0 100.00 1 200.00 2 NaN 3 300.12 4 400.00 dtype: float64

In [15]:
# Original Data Series
s = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s)

# Change the data type to numeric, coercing errors to NaN
s_numeric = pd.to_numeric(s, errors='coerce')
print("\nChanged to numeric data type:")
print(s_numeric)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Changed to numeric data type:
0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64



---
```8``` Write a Python Pandas program to convert the first column of a DataFrame as a Series. Sample Output: Original DataFrame col1 col2 col3 0 1 4 7 1 2 5 5 2 3 6 8 3 4 9 12 4 7 5 1 5 11 0 11 1st column as a Series: 0 1 1 2 2 3 3 4 4 7 5 11 Name: col1, dtype: int64 <class 'pandas.core.series.Series'>

In [16]:
# Original DataFrame
df = pd.DataFrame({
    'col1': [1, 2, 3, 4, 7, 11],
    'col2': [4, 5, 6, 9, 5, 0],
    'col3': [7, 5, 8, 12, 1, 11]
})
print("Original DataFrame:")
print(df)

# Convert the first column to a Series
col1_series = df['col1']
print("\n1st column as a Series:")
print(col1_series)
print(type(col1_series))

Original DataFrame:
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11

1st column as a Series:
0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64
<class 'pandas.core.series.Series'>


---
```9``` Write a Pandas program to convert a given Series to an array. Sample Output: Original Data Series: 0 100 1 200 2 python 3 300.12 4 400 dtype: object Series to an array ['100' '200' 'python' '300.12' '400']



In [17]:
s = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s)

# Convert Series to a NumPy array
np_array = s.to_numpy()
print("\nSeries to an array:")
print(np_array)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Series to an array:
['100' '200' 'python' '300.12' '400']


---
```10``` Write a Pandas program to convert Series of lists to one Series. Sample Output: Original Series of list 0 [Red, Green, White] 1 [Red, Black] 2 [Yellow] dtype: object One Series 0 Red 1 Green 2 White 3 Red 4 Black 5 Yellow dtype: object

In [18]:
s = pd.Series([['Red', 'Green', 'White'], ['Red', 'Black'], ['Yellow']])
print("Original Series of list:")
print(s)

# Use explode to create one Series
s_flat = s.explode()
print("\nOne Series:")
print(s_flat)

Original Series of list:
0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object

One Series:
0       Red
0     Green
0     White
1       Red
1     Black
2    Yellow
dtype: object


---
```11``` Write a Pandas program to convert Series of lists to one Series. Sample Output: Original Series of list 0 [Red, Green, White] 1 [Red, Black] 2 [Yellow] dtype: object One Series 0 Red 1 Green 2 White 3 Red 4 Black 5 Yellow dtype: object

In [19]:
# Create the original Series containing lists
s = pd.Series([
    ['Red', 'Green', 'White'], 
    ['Red', 'Black'], 
    ['Yellow']
])

# Use .explode() to transform each list item into its own row
s_exploded = s.explode()

# Reset the index to match the sample output
s_final = s_exploded.reset_index(drop=True)

print("Original Series of list:")
print(s)
print("\nOne Series:")
print(s_final)


Original Series of list:
0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object

One Series:
0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object


---
```12``` Write a Pandas program to add some data to an existing Series. Sample Output: Original Data Series: 0 100 1 200 2 python 3 300.12 4 400 dtype: object Data Series after adding some data: 0 100 1 200 2 python 3 300.12 4 400 0 500 1 php dtype: object

In [20]:
s = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s)

# New data to add
new_data = pd.Series(['500', 'php'])

# Add the new data using concat
s_extended = pd.concat([s, new_data], ignore_index=True)

print("\nData Series after adding some data:")
print(s_extended)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Data Series after adding some data:
0       100
1       200
2    python
3    300.12
4       400
5       500
6       php
dtype: object


---

```END OF ASSIGNMENT```

---

## Assessment

#### See the attached datasets in Data Analysis folder ``` Beijing_PEK_2014.csv, Brasilia_BSB_2014.csv, CapeTown_CPT_2014.csv, Delhi_DEL_2014.csv, London_2014.csv, and Moscow_SVO_2014.csv.``` Explore them, run your analysis on them, and detail your findings below as much as you can.

---
## findings

Dataset Overview Report
### 1. General Summary

The dataset contains daily weather records for six global cities, Beijing, Brasilia, Cape Town, Delhi, London, and Moscow each covering one full year (365 rows and 23 columns).
Columns capture temperature, humidity, visibility, wind speed, and event types such as rain, fog, or snow.
Some columns (e.g., ' Max Gust SpeedKm/h', ' CloudCover', ' Events') contain many missing entries, suggesting incomplete recording for certain days.

### 2. Data Structure and Quality

* Rows and Columns: Each city dataset has a uniform structure: 365 days × 23 columns.

* Data Types: Mostly numerical (int64, float64) with categorical (object) columns for Date and Events.

* Missing Data: Common across all cities, especially in ' Events', ' CloudCover', and ' Max Gust SpeedKm/h'.

* Naming Anomalies: Several columns include leading spaces or HTML remnants (e.g., 'WindDirDegrees<br />'), indicating an unclean export.

### 3. Categorical Insights (Events)

* Rain is the most frequently recorded event in most cities.

* London has the highest number of rainy days (202), confirming its wet climate.

* Beijing and Delhi contain many days with no recorded events (243+ and 273 NaN values respectively).

* Moscow alternates between Snow (73) and Rain (70), matching cold-season weather patterns.

* Brasilia experiences many Rain-Thunderstorm days (75), consistent with tropical weather behavior.

### 4. Grouped Averages (by Event Type)

* Grouping by event type reveals distinct trends:

* Rain and Thunderstorm days typically show higher mean temperatures but moderate humidity.

* Fog and Snow days consistently correspond to lower temperatures and higher humidity.

For example:

- In London, foggy days average 10°C and 77% humidity, while Rain-Thunderstorm days rise to 16°C with lower humidity (~74%).

- In Moscow, Snow days average –6°C with 83% humidity, confirming cold, moist air conditions.

- Delhi shows an inverse pattern, Thunderstorms occur at high temperatures (~22°C) but with low humidity (~40%).

### 5. Overall Interpretation

* The datasets successfully capture annual climate behavior for multiple regions.

* Rain and Fog are the most recurrent weather types globally, though their temperature-humidity relationship varies by geography.

* The presence of incomplete event data (NaN) likely represents calm or unreported days rather than true missing records.

* Overall, the datasets provide a solid foundation for studying climate variability, event correlation, and seasonal weather patterns across continents.

``` scroll down under 'analysis' to see my code for this ```

---

# Link to your publication

## [hashnode](https://nerdyalgorithm.hashnode.dev/week-6-at-dataraflow)

---
## Analysis

In [21]:
import pandas as pd
import numpy as np

print("Libraries imported!")

Libraries imported!


In [22]:
# i was getting a lot of runtime warning since i am using kaggle, so this is me clearing it

import warnings
warnings.filterwarnings("ignore", category=RuntimeWarning)

In [23]:
# Define the file paths for the datasets
files_to_load = {
    "Beijing": "/kaggle/input/dataraflow-data-analysis-dataset/Beijing_PEK_2014.csv",
    "Brasilia": "/kaggle/input/dataraflow-data-analysis-dataset/Brasilia_BSB_2014.csv",
    "Cape Town": "/kaggle/input/dataraflow-data-analysis-dataset/CapeTown_CPT_2014.csv",
    "Delhi": "/kaggle/input/dataraflow-data-analysis-dataset/Delhi_DEL_2014.csv",
    "London": "/kaggle/input/dataraflow-data-analysis-dataset/London_2014.csv",
    "Moscow": "/kaggle/input/dataraflow-data-analysis-dataset/Moscow_SVO_2014.csv"
}

# Create an empty dictionary to store the loaded DataFrames
datasets = {}

print("--- Loading All Datasets ---")
# Loop through each file, load it with pd.read_csv, and store it
for city_name, file_path in files_to_load.items():
    try:
        # Load the file normally first
        datasets[city_name] = pd.read_csv(file_path)
        print(f"Successfully loaded {city_name}")
    except Exception as e:
        print(f"Error loading {city_name}: {e}")

print("--- Initial data loading complete ---")

--- Loading All Datasets ---
Successfully loaded Beijing
Successfully loaded Brasilia
Successfully loaded Cape Town
Successfully loaded Delhi
Successfully loaded London
Successfully loaded Moscow
--- Initial data loading complete ---


In [24]:
for city_name, df in datasets.items():
    print(f"\n--- HEAD for {city_name} ---")
    print(df.head())


--- HEAD for Beijing ---
       Date  Max TemperatureC  Mean TemperatureC  Min TemperatureC  \
0  2014-1-1                12                  4                -2   
1  2014-1-2                 7                  0                -6   
2  2014-1-3                 9                  3                -2   
3  2014-1-4                 2                 -2                -6   
4  2014-1-5                 7                  0                -7   

   Dew PointC  MeanDew PointC  Min DewpointC  Max Humidity   Mean Humidity  \
0         -12             -17            -20            44              19   
1          -6              -9            -13            74              50   
2          -7             -13            -18            64              32   
3          -4              -7             -9            80              68   
4          -5             -11            -15            80              51   

    Min Humidity  ...   Max VisibilityKm   Mean VisibilityKm  \
0              7  ..

In [25]:
# --- BASIC OVERVIEW OF EACH CITY DATASET ---

# Loop through each city and its DataFrame in the 'datasets' dictionary
for city_name, df in datasets.items():
    print(f"\n=== {city_name} Dataset Overview ===")

    # 1. Show the shape — tells how many rows and columns are in the dataset
    print("Shape:", df.shape)

    # 2. Show info — gives column names, data types, and count of non-missing values
    print("\nInfo:")
    print(df.info())

    # 3. Print a separator line for readability between each city’s output
    print("-" * 50)



=== Beijing Dataset Overview ===
Shape: (365, 23)

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Date                         365 non-null    object 
 1   Max TemperatureC             365 non-null    int64  
 2   Mean TemperatureC            365 non-null    int64  
 3   Min TemperatureC             365 non-null    int64  
 4   Dew PointC                   365 non-null    int64  
 5   MeanDew PointC               365 non-null    int64  
 6   Min DewpointC                365 non-null    int64  
 7   Max Humidity                 365 non-null    int64  
 8    Mean Humidity               365 non-null    int64  
 9    Min Humidity                365 non-null    int64  
 10   Max Sea Level PressurehPa   365 non-null    int64  
 11   Mean Sea Level PressurehPa  365 non-null    int64  
 12   Min Sea Level Press

In [26]:
# --- NUMERICAL SUMMARY USING .describe() ---

# Loop through each city dataset again
for city_name, df in datasets.items():
    print(f"\n=== {city_name} Dataset: Statistical Summary ===")
    
    # .describe() gives quick statistics for all numerical columns
    # Includes count, mean, std (standard deviation), min, max, and quartiles
    print(df.describe())
    
    # Add a separator for clarity
    print("-" * 50)



=== Beijing Dataset: Statistical Summary ===
       Max TemperatureC  Mean TemperatureC  Min TemperatureC  Dew PointC  \
count        365.000000         365.000000        365.000000  365.000000   
mean          19.523288          13.364384          7.542466    6.580822   
std           11.249060          10.937703         11.032742   12.328479   
min           -2.000000          -7.000000        -13.000000  -24.000000   
25%            9.000000           3.000000         -3.000000   -4.000000   
50%           22.000000          14.000000          9.000000    9.000000   
75%           30.000000          23.000000         18.000000   18.000000   
max           42.000000          31.000000         27.000000   25.000000   

       MeanDew PointC  Min DewpointC  Max Humidity   Mean Humidity  \
count      365.000000     365.000000    365.000000      365.000000   
mean         2.123288      -2.465753     78.630137       50.753425   
std         13.762452      15.056015     18.203299       19

In [27]:
# --- CHECK ACTUAL COLUMN NAMES ---

# Loop through each city and print the exact list of column names
for city_name, df in datasets.items():
    print(f"\n=== {city_name} Columns ===")
    
    # List all column names to see if there are extra spaces or special characters
    print(df.columns.tolist())
    
    print("-" * 50)



=== Beijing Columns ===
['Date', 'Max TemperatureC', 'Mean TemperatureC', 'Min TemperatureC', 'Dew PointC', 'MeanDew PointC', 'Min DewpointC', 'Max Humidity', ' Mean Humidity', ' Min Humidity', ' Max Sea Level PressurehPa', ' Mean Sea Level PressurehPa', ' Min Sea Level PressurehPa', ' Max VisibilityKm', ' Mean VisibilityKm', ' Min VisibilitykM', ' Max Wind SpeedKm/h', ' Mean Wind SpeedKm/h', ' Max Gust SpeedKm/h', 'Precipitationmm', ' CloudCover', ' Events', 'WindDirDegrees<br />']
--------------------------------------------------

=== Brasilia Columns ===
['Date', 'Max TemperatureC', 'Mean TemperatureC', 'Min TemperatureC', 'Dew PointC', 'MeanDew PointC', 'Min DewpointC', 'Max Humidity', ' Mean Humidity', ' Min Humidity', ' Max Sea Level PressurehPa', ' Mean Sea Level PressurehPa', ' Min Sea Level PressurehPa', ' Max VisibilityKm', ' Mean VisibilityKm', ' Min VisibilitykM', ' Max Wind SpeedKm/h', ' Mean Wind SpeedKm/h', ' Max Gust SpeedKm/h', 'Precipitationmm', ' CloudCover', ' Eve

In [28]:
# --- VALUE COUNTS FOR WEATHER EVENTS (correct column name with space) ---

# Loop through each city dataset
for city_name, df in datasets.items():
    print(f"\n=== {city_name} Dataset: Event Frequency ===")
    
    # Using the correct column name: ' Events' 
    # .value_counts() will show how many times each weather event appears
    # dropna=False ensures missing values are also shown in the count
    print(df[' Events'].value_counts(dropna=False))
    
    # Separator line for clarity
    print("-" * 50)



=== Beijing Dataset: Event Frequency ===
 Events
NaN                      243
Rain                      44
Rain-Thunderstorm         33
Fog                       28
Snow                       7
Fog-Rain                   5
Fog-Snow                   2
Fog-Rain-Thunderstorm      2
Thunderstorm               1
Name: count, dtype: int64
--------------------------------------------------

=== Brasilia Dataset: Event Frequency ===
 Events
NaN                       203
Rain-Thunderstorm          75
Rain                       41
Thunderstorm               30
Fog-Rain-Thunderstorm       6
Fog                         6
Fog-Thunderstorm            2
Fog-Rain                    1
Rain-Hail-Thunderstorm      1
Name: count, dtype: int64
--------------------------------------------------

=== Cape Town Dataset: Event Frequency ===
 Events
NaN                  229
Rain                  87
Fog                   38
Fog-Rain               8
Rain-Thunderstorm      2
Rain-Snow              1
Name: count,

In [29]:
# --- GROUPED ANALYSIS: AVERAGE TEMPERATURE AND HUMIDITY BY EVENT ---

# Loop through each city dataset
for city_name, df in datasets.items():
    print(f"\n=== {city_name}: Average Weather by Event ===")
    
    # Group the dataset by the ' Events' column 
    # Then calculate the mean of selected numeric columns for each event type
    grouped = df.groupby(' Events')[['Mean TemperatureC', ' Mean Humidity']].mean()
    
    # Display the grouped mean values
    print(grouped)
    
    # Separator for clarity
    print("-" * 50)



=== Beijing: Average Weather by Event ===
                       Mean TemperatureC   Mean Humidity
 Events                                                 
Fog                             6.607143       62.178571
Fog-Rain                        7.400000       80.200000
Fog-Rain-Thunderstorm          19.000000       85.500000
Fog-Snow                       -1.500000       61.500000
Rain                           19.750000       61.977273
Rain-Thunderstorm              23.545455       67.030303
Snow                           -2.000000       58.285714
Thunderstorm                   25.000000       60.000000
--------------------------------------------------

=== Brasilia: Average Weather by Event ===
                        Mean TemperatureC   Mean Humidity
 Events                                                  
Fog                             21.500000       68.500000
Fog-Rain                        22.000000       67.000000
Fog-Rain-Thunderstorm           23.666667       75.666667
Fo

# ```THE END```